package org.mule.extension.agent.composer.internal.values;

import org.mule.runtime.api.value.Value;
import org.mule.runtime.extension.api.values.ValueBuilder;
import org.mule.runtime.extension.api.values.ValueProvider;
import org.mule.runtime.extension.api.values.ValueResolvingException;
import org.mule.runtime.http.api.HttpService;
import org.mule.runtime.http.api.server.HttpServer;
import org.mule.runtime.http.api.server.ServerNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Provides a dropdown of available HTTP Listener Config names by probing
 * well-known port/name conventions via the Mule {@link HttpService}.
 *
 * <p>Because the SDK does not expose a registry-level enumeration of all
 * registered {@code <http:listener-config>} global elements, this provider
 * attempts lookups against the names of servers that have already been
 * started and registered with the HTTP service. If none are found it falls
 * back to offering {@code "HTTP_Listener_config"} (the Anypoint Studio default).
 */
public class HttpListenerConfigValueProvider implements ValueProvider {

    private static final Logger LOGGER = LoggerFactory.getLogger(HttpListenerConfigValueProvider.class);

    /**
     * Common default names generated by Anypoint Studio when scaffolding HTTP listeners.
     * The provider probes these names first, then surfaces only those that resolve successfully.
     */
    private static final String[] CANDIDATE_NAMES = {
            "HTTP_Listener_config",
            "HTTP_Listener_Config",
            "HTTP_Listener",
            "HTTPListenerConfig",
            "httpListenerConfig",
            "api-httpListenerConfig",
    };

    @Inject
    private HttpService httpService;

    @Override
    public Set<Value> resolve() throws ValueResolvingException {
        Set<Value> values = new LinkedHashSet<>();

        if (httpService != null) {
            for (String candidate : CANDIDATE_NAMES) {
                try {
                    HttpServer server = httpService.getServerFactory().lookup(candidate);
                    if (server != null) {
                        values.add(ValueBuilder.newValue(candidate).build());
                    }
                } catch (ServerNotFoundException ignored) {
                    // not registered — skip
                } catch (Exception e) {
                    LOGGER.debug("Probe failed for HTTP Listener Config '{}': {}", candidate, e.getMessage());
                }
            }
        }

        // Always include the Studio default so the dropdown is never empty
        values.add(ValueBuilder.newValue("HTTP_Listener_config").build());
        return values;
    }
}
