package org.mule.extension.agent.composer.internal.model;

/**
 * Normalised response from an LLM inference call.
 *
 * Stop-reason semantics (provider-agnostic):
 *  - {@code "stop"}     – model reached a natural end; {@code content} is the final answer.
 *  - {@code "tool_use"} – model requested a tool call; inspect {@code toolCall}.
 */
public class LlmResponse {

    private String content;
    private ToolCall toolCall;

    /**
     * Normalised stop reason:
     *  OpenAI  → "stop" | "tool_calls"
     *  Anthropic → "end_turn" | "tool_use"
     * Stored as returned by the provider; {@link #hasFinalAnswer()} abstracts over both.
     */
    private String stopReason;

    /** Tokens consumed by the prompt / context sent to the model. */
    private int inputTokens;

    /** Tokens generated by the model in this response. */
    private int outputTokens;

    // ── constructors ──────────────────────────────────────────────────────────

    public LlmResponse() {}

    public LlmResponse(String content, ToolCall toolCall, String stopReason) {
        this.content = content;
        this.toolCall = toolCall;
        this.stopReason = stopReason;
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    /** Returns {@code true} when the LLM has produced a final text answer. */
    public boolean hasFinalAnswer() {
        return toolCall == null;
    }

    /** Returns {@code true} when the LLM is requesting a tool invocation. */
    public boolean hasToolCall() {
        return toolCall != null;
    }

    // ── getters / setters ─────────────────────────────────────────────────────

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    public ToolCall getToolCall() { return toolCall; }
    public void setToolCall(ToolCall toolCall) { this.toolCall = toolCall; }

    public String getStopReason() { return stopReason; }
    public void setStopReason(String stopReason) { this.stopReason = stopReason; }

    public int getInputTokens() { return inputTokens; }
    public void setInputTokens(int inputTokens) { this.inputTokens = inputTokens; }

    public int getOutputTokens() { return outputTokens; }
    public void setOutputTokens(int outputTokens) { this.outputTokens = outputTokens; }
}
