package org.mule.extension.agent.composer.internal.model;

import java.util.Collections;
import java.util.List;

/**
 * Normalised response from an LLM inference call.
 *
 * Stop-reason semantics (provider-agnostic):
 *  - {@code "stop"}     – model reached a natural end; {@code content} is the final answer.
 *  - {@code "tool_use"} – model requested one or more tool calls; inspect {@code toolCalls}.
 */
public class LlmResponse {

    private String content;

    /**
     * All tool calls requested in this response. May contain multiple entries when the
     * LLM requests parallel tool execution. Empty (never null) when there are no tool calls.
     */
    private List<ToolCall> toolCalls = Collections.emptyList();

    /**
     * Normalised stop reason:
     *  OpenAI  → "stop" | "tool_calls"
     *  Anthropic → "end_turn" | "tool_use"
     * Stored as returned by the provider; {@link #hasFinalAnswer()} abstracts over both.
     */
    private String stopReason;

    /** Tokens consumed by the prompt / context sent to the model. */
    private int inputTokens;

    /** Tokens generated by the model in this response. */
    private int outputTokens;

    // ── constructors ──────────────────────────────────────────────────────────

    public LlmResponse() {}

    public LlmResponse(String content, ToolCall toolCall, String stopReason) {
        this.content = content;
        this.toolCalls = toolCall != null ? Collections.singletonList(toolCall) : Collections.emptyList();
        this.stopReason = stopReason;
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    /** Returns {@code true} when the LLM has produced a final text answer (no tool calls). */
    public boolean hasFinalAnswer() {
        return toolCalls == null || toolCalls.isEmpty();
    }

    /** Returns {@code true} when the LLM is requesting one or more tool invocations. */
    public boolean hasToolCall() {
        return toolCalls != null && !toolCalls.isEmpty();
    }

    // ── getters / setters ─────────────────────────────────────────────────────

    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }

    /**
     * All tool calls in this response. Use this when you need to handle parallel tool execution.
     * Returns an empty list (never null) when there are no tool calls.
     */
    public List<ToolCall> getToolCalls() {
        return toolCalls != null ? toolCalls : Collections.emptyList();
    }
    public void setToolCalls(List<ToolCall> toolCalls) {
        this.toolCalls = toolCalls != null ? toolCalls : Collections.emptyList();
    }

    /**
     * Convenience accessor returning the first tool call, or {@code null} if none.
     * Prefer {@link #getToolCalls()} for full parallel-tool support.
     */
    public ToolCall getToolCall() {
        return (toolCalls != null && !toolCalls.isEmpty()) ? toolCalls.get(0) : null;
    }
    public void setToolCall(ToolCall toolCall) {
        this.toolCalls = toolCall != null ? Collections.singletonList(toolCall) : Collections.emptyList();
    }

    public String getStopReason() { return stopReason; }
    public void setStopReason(String stopReason) { this.stopReason = stopReason; }

    public int getInputTokens() { return inputTokens; }
    public void setInputTokens(int inputTokens) { this.inputTokens = inputTokens; }

    public int getOutputTokens() { return outputTokens; }
    public void setOutputTokens(int outputTokens) { this.outputTokens = outputTokens; }
}
